torch_start_method: 'forkserver'
randomseed: 0


last_epoch: 150
resume_epoch: 0

GPGPU:
  device_ids: [0]

model: /root/clssl/results_-10+10_scl+doa_50+40/model_checkpoint/best_model.tar  # only for fine-tuning

SCL: True
trained_scl_model_path: /root/clssl/experiment_5/results_sigma2_scl_1100/model_checkpoint/best_model.tar   # for scl