torch_start_method: 'spawn'
randomseed: 0


last_epoch: 400
resume_epoch: 0

GPGPU:
  device_ids: [0]

SCL: True
finetune: False
# finetune : False
trained_scl_model_path: ./results_02111440_scl/model_checkpoint/best_model.tar   # for initial scl+doa training
# finetune : True
model_for_finetune: ./results_02122120_scl/model_checkpoint/best_model.tar  # only for fine-tuning
