torch_start_method: 'spawn'
randomseed: 0

acc_threshold: 10
local_maximum_distance: 30

last_epoch: 400
resume_epoch: 0

GPGPU:
  device_ids: [0]

SCL: False
finetune: False
# finetune : False
trained_scl_model_path: ./results_03181719_scl/model_checkpoint/best_model.tar   # for initial scl+doa training
# finetune : True
model_for_finetune: ./results/model_checkpoint/last_model.tar  # only for fine-tuning
